{{- if include "nullOrEmpty" (list .Values.secrets "existingSecret") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
data:
  adminUser: {{ .Values.secrets.adminUser }}
  adminPassword: {{ .Values.secrets.adminPassword }}
  selfhostdeUser: {{ .Values.secrets.selfhostdeUser }}
  selfhostdePassword: {{ .Values.secrets.selfhostdePassword }}
  selfhostdeRecordId: {{ .Values.secrets.selfhostdeRecordId }}
{{- end }}
